PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS project_audit_sessions (id TEXT PRIMARY KEY, project_path TEXT NOT NULL, audit_type TEXT NOT NULL, status TEXT NOT NULL, started_at TEXT NOT NULL, completed_at TEXT, warnings_json TEXT NOT NULL DEFAULT '[]');
CREATE TABLE IF NOT EXISTS project_findings (id TEXT PRIMARY KEY, audit_session_id TEXT NOT NULL, code TEXT NOT NULL, severity TEXT NOT NULL, title TEXT NOT NULL, evidence_path TEXT, line_number INTEGER, redacted_preview TEXT, weight INTEGER NOT NULL DEFAULT 0, FOREIGN KEY(audit_session_id) REFERENCES project_audit_sessions(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS project_dependencies (id TEXT PRIMARY KEY, project_path TEXT NOT NULL, name TEXT NOT NULL, version TEXT NOT NULL, dependency_type TEXT NOT NULL, source_manifest TEXT NOT NULL, is_pinned INTEGER NOT NULL DEFAULT 0, audited_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS project_command_runs (id TEXT PRIMARY KEY, project_path TEXT NOT NULL, task_id TEXT NOT NULL, command_preview TEXT NOT NULL, status TEXT NOT NULL, exit_code INTEGER, duration_ms INTEGER, stdout_preview TEXT, stderr_preview TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS project_environment_keys (id TEXT PRIMARY KEY, project_path TEXT NOT NULL, key_name TEXT NOT NULL, present_runtime INTEGER NOT NULL, present_template INTEGER NOT NULL, empty_value INTEGER NOT NULL, duplicate_count INTEGER NOT NULL, audited_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS project_source_metrics (id TEXT PRIMARY KEY, project_path TEXT NOT NULL, metrics_json TEXT NOT NULL, audited_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS project_cache_targets (id TEXT PRIMARY KEY, project_path TEXT NOT NULL, absolute_path TEXT NOT NULL, category TEXT NOT NULL, size_bytes INTEGER NOT NULL, safe_to_clean INTEGER NOT NULL, audited_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS project_git_snapshots (id TEXT PRIMARY KEY, project_path TEXT NOT NULL, snapshot_json TEXT NOT NULL, audited_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS project_runtime_processes (id TEXT PRIMARY KEY, project_path TEXT NOT NULL, pid INTEGER NOT NULL, process_name TEXT NOT NULL, evidence_json TEXT NOT NULL, audited_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS project_reports (id TEXT PRIMARY KEY, project_path TEXT NOT NULL, format TEXT NOT NULL, exported_path TEXT NOT NULL, size_bytes INTEGER NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_project_audits_path ON project_audit_sessions(project_path, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_project_findings_session ON project_findings(audit_session_id);
CREATE INDEX IF NOT EXISTS idx_project_reports_path ON project_reports(project_path, created_at DESC);
