/**
 * KNOUX ONE — Explicit allowlisted native command registry.
 * Never construct Tauri command names from user-controlled handler IDs.
 */
export const NATIVE_COMMANDS = {
  'm01.system.discover': 'm01_system_discover_complete',
  'm01.winget.verify': 'm01_winget_verify',
  'm01.winget.install': 'm01_winget_install_queued',
  'm01.winget.queue.list': 'm01_winget_queue_list',
  'm01.winget.queue.resume': 'm01_winget_queue_resume',
  'm02.cleanup.scan': 'm02_cleanup_scan_complete',
  'm02.cleanup.execute': 'm02_cleanup_execute_complete',
  'm02.cleanup.cancel': 'm02_cleanup_cancel_complete',
  'm02.cleanup.history': 'm02_cleanup_history_complete',
  'm02.scan.user_temp': 'm02_scan_user_temp',
  'm02.scan.windows_temp': 'm02_scan_windows_temp_complete',
  'm02.scan.browser_cache': 'm02_scan_browser_cache',
  'm02.scan.thumbnail_cache': 'm02_scan_thumbnail_cache',
  'm02.scan.crash_dumps': 'm02_scan_crash_dumps_complete',
  'm02.scan.application_logs': 'm02_scan_application_logs_complete',
  'm02.scan.old_downloads': 'm02_scan_old_downloads_complete',
  'm02.downloads.quarantine.list': 'm02_download_quarantine_list',
  'm02.downloads.quarantine.restore': 'm02_download_quarantine_restore',
  'm03.scan.exact': 'm03_scan_exact',
  'm03.scan.fast': 'm03_scan_fast',
  'm03.scan.images': 'm03_scan_images_complete',
  'm03.scan.videos': 'm03_scan_videos_complete',
  'm03.scan.audio': 'm03_scan_audio_complete',
  'm03.scan.documents': 'm03_scan_documents',
  'm03.scan.archives': 'm03_scan_archives_complete',
  'm03.scan.folders': 'm03_scan_folders',
  'm03.keeper.plan': 'm03_keeper_plan',
  'm03.quarantine.manage': 'm03_quarantine_manage',
  'm03.job.pause': 'm03_job_pause',
  'm03.job.resume': 'm03_job_resume',
  'm03.job.cancel': 'm03_job_cancel',
  'm03.job.list': 'm03_job_list',
  'm03.scan.history': 'm03_scan_history',
  'm03.scan.result': 'm03_scan_result',
  'm03.folder.pick': 'm03_pick_folder',
  'm04.storage.scan': 'm04_storage_scan_complete',
  'm04.files.largest': 'm04_largest_files',
  'm04.folders.largest': 'm04_largest_folders',
  'm04.types.distribution': 'm04_type_distribution',
  'm04.files.old': 'm04_old_files_complete',
  'm04.downloads.analyze': 'm04_downloads_complete',
  'm04.appdata.analyze': 'm04_appdata_complete',
  'm04.drives.external': 'm04_external_drives_complete',
  'm04.space.check': 'm04_space_check_complete',
  'm04.report.export': 'm04_report_export_complete',
  'm04.scan.cancel': 'm04_scan_cancel_complete',
  'm05.registry.inspect': 'm05_registry_entries',
  'm05.folders.inspect': 'm05_startup_folders',
  'm05.tasks.inspect': 'm05_scheduled_tasks',
  'm05.services.inspect': 'm05_windows_services',
  'm05.impact.assess': 'm05_impact_assess',
  'm05.recommendations.generate': 'm05_recommendations',
  'm05.startup.change': 'm05_startup_change',
  'm05.delay.manage': 'm05_delay_manage',
  'm05.profiles.manage': 'm05_profiles_manage',
  'm05.restore.manage': 'm05_restore_manage',
  'm05.boot.history': 'm05_boot_history',
  'm06.cpu.monitor': 'm06_cpu_monitor',
  'm06.memory.monitor': 'm06_memory_monitor',
  'm06.disk.activity': 'm06_disk_activity',
  'm06.network.activity': 'm06_network_activity',
  'm06.process.explorer': 'm06_process_explorer',
  'm06.process.heavy': 'm06_heavy_processes',
  'm06.priority.manage': 'm06_priority_manage',
  'm06.power.manage': 'm06_power_plans_manage',
  'm06.profiles.manage': 'm06_profiles_manage',
  'm06.benchmark.report': 'm06_benchmark_report',
  'm07.sfc.manage': 'm07_sfc_manage',
  'm07.dism.check_health': 'm07_dism_check_health',
  'm07.dism.scan_health': 'm07_dism_scan_health',
  'm07.dism.restore_health': 'm07_dism_restore_health',
  'm07.update.manage': 'm07_windows_update_manage',
  'm07.cache.manage': 'm07_cache_manage',
  'm07.wmi.manage': 'm07_wmi_manage',
  'm07.installer.manage': 'm07_installer_manage',
  'm07.vss.manage': 'm07_vss_manage',
  'm07.store.manage': 'm07_store_manage',
  'm08.adapters.inspect': 'm08_adapter_inventory',
  'm08.ip.inspect': 'm08_ip_configuration',
  'm08.ping.test': 'm08_ping_test',
  'm08.traceroute.run': 'm08_traceroute',
  'm08.dns.benchmark': 'm08_dns_benchmark',
  'm08.dns.flush': 'm08_flush_dns',
  'm08.ip.renew': 'm08_renew_ip',
  'm08.stack.reset': 'm08_stack_reset',
  'm08.proxy_firewall.inspect': 'm08_proxy_firewall_status',
  'm08.report.export': 'm08_report_export',
  'm15.environment.discover': 'm15_environment_discover',
  'm15.path.audit': 'm15_path_audit',
  'm15.runtime.inspect': 'm15_runtime_inspect',
  'm15.git.audit': 'm15_git_audit',
  'm15.repositories.scan': 'm15_repositories_scan',
  'm15.ports.manage': 'm15_ports_manage',
  'm15.projects.audit': 'm15_projects_audit',
  'm15.caches.manage': 'm15_caches_manage',
  'm15.http.execute': 'm15_http_execute',
  'm15.report.export': 'm15_report_export',
} as const;

export type NativeHandlerId = keyof typeof NATIVE_COMMANDS;
export function resolveNativeCommand(handlerId: string): string | null {
  return Object.prototype.hasOwnProperty.call(NATIVE_COMMANDS, handlerId)
    ? NATIVE_COMMANDS[handlerId as NativeHandlerId]
    : null;
}
