/** KNOUX ONE — Module 03 Scan Builder */
import React, { useState } from 'react';
import { Archive, FileAudio, FileText, FolderMinus, FolderPlus, FolderTree, Image, Play, Settings, ShieldCheck, Video, Zap } from 'lucide-react';
import { useTranslation } from '../../i18n';
import type { DuplicateScanMode } from './duplicateContracts';

export function DuplicateScanSetup({store}:{store:any}){
 const {t}=useTranslation(); const [manualPath,setManualPath]=useState('');
 const addManualPath=()=>{const value=manualPath.trim();if(!value)return;store.setScanConfig((previous:any)=>({...previous,targetPaths:previous.targetPaths.includes(value)?previous.targetPaths:[...previous.targetPaths,value]}));setManualPath('');};
 const scanModes:Array<{mode:DuplicateScanMode;icon:React.ElementType;titleEn:string;titleAr:string;descriptionEn:string;descriptionAr:string;state:'implemented'|'partial'}>=[
  {mode:'exact_blake3',icon:Zap,titleEn:'Exact BLAKE3 verification',titleAr:'التحقق التام عبر BLAKE3',descriptionEn:'Size grouping, partial samples, full streaming hash, change revalidation, and hard-link awareness.',descriptionAr:'تجميع بالحجم ثم بصمة جزئية وكاملة مع إعادة التحقق واكتشاف الروابط الصلبة.',state:'implemented'},
  {mode:'fast_partial',icon:Zap,titleEn:'Fast candidate scan',titleAr:'الفحص السريع للمرشحين',descriptionEn:'Creates candidates only. Full verification is mandatory before quarantine.',descriptionAr:'ينشئ مرشحين فقط، ولا يسمح بالمحجر قبل التحقق الكامل.',state:'implemented'},
  {mode:'similar_images',icon:Image,titleEn:'Similar image review',titleAr:'مراجعة الصور المتشابهة',descriptionEn:'Exact hashes plus local perceptual dHash comparison. Similar files require manual review.',descriptionAr:'بصمة تامة مع مقارنة بصرية محلية، والملفات المتشابهة تحتاج مراجعة يدوية.',state:'partial'},
  {mode:'video_streams',icon:Video,titleEn:'Video duplicate review',titleAr:'مراجعة الفيديوهات المكررة',descriptionEn:'Exact file verification is active. Advanced stream similarity requires ffprobe.',descriptionAr:'التحقق التام للملف متاح، أما تشابه المسارات المتقدم فيحتاج ffprobe.',state:'partial'},
  {mode:'audio_fingerprint',icon:FileAudio,titleEn:'Audio duplicate review',titleAr:'مراجعة الملفات الصوتية',descriptionEn:'Exact duplicates are active. Acoustic fingerprinting requires a reviewed optional engine.',descriptionAr:'اكتشاف النسخ التامة متاح، والبصمة الصوتية تحتاج محركًا اختياريًا معتمدًا.',state:'partial'},
  {mode:'documents',icon:FileText,titleEn:'Document duplicate verification',titleAr:'التحقق من المستندات المكررة',descriptionEn:'Local exact hashing for PDF, Office, text, configuration, and source-code files.',descriptionAr:'بصمة محلية تامة لملفات PDF وOffice والنصوص والإعدادات والكود.',state:'implemented'},
  {mode:'archives',icon:Archive,titleEn:'Archive duplicate review',titleAr:'مراجعة الأرشيفات المكررة',descriptionEn:'Exact archive verification without unsafe automatic extraction.',descriptionAr:'تحقق تام من ملفات الأرشيف دون فك ضغط تلقائي غير آمن.',state:'partial'},
  {mode:'folder_structures',icon:FolderTree,titleEn:'Folder structure comparison',titleAr:'مقارنة هياكل المجلدات',descriptionEn:'Deterministic folder digests and item-level overlap evidence.',descriptionAr:'بصمة حتمية للمجلدات مع أدلة تفصيلية للعناصر المتطابقة والمختلفة.',state:'implemented'},
 ];
 return <div className="grid gap-6 xl:grid-cols-[minmax(320px,.85fr)_minmax(0,1.8fr)]">
  <div className="space-y-5">
   <section className="knoux-glass-panel p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 text-base font-black text-[var(--knoux-text)]"><FolderPlus className="h-5 w-5 text-blue-400"/>{t('Scan sources','مصادر الفحص')}</h2><p className="mt-1 text-xs leading-6 text-[var(--knoux-subtext)]">{t('Choose local folders or enter a trusted absolute path.','اختر مجلدات محلية أو أدخل مسارًا مطلقًا موثوقًا.')}</p></div><button type="button" onClick={store.selectFolder} disabled={!store.runtime.available} className="knoux-btn-secondary text-xs disabled:opacity-50">{t('Browse','استعراض')}</button></div>
   <div className="mt-4 flex gap-2"><input value={manualPath} onChange={event=>setManualPath(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')addManualPath();}} placeholder="C:\\Users\\Name\\Pictures" className="knoux-input min-w-0 flex-1 font-mono text-xs" dir="ltr"/><button type="button" onClick={addManualPath} className="knoux-btn-primary px-4 text-xs">{t('Add','إضافة')}</button></div>
   <div className="mt-4 space-y-2">{store.scanConfig.targetPaths.length===0?<div className="rounded-xl border border-dashed border-[var(--knoux-border)] p-5 text-center text-xs text-[var(--knoux-subtext)]">{t('No scan source selected.','لم يتم اختيار مصدر للفحص.')}</div>:store.scanConfig.targetPaths.map((path:string)=><div key={path} className="flex items-center gap-2 rounded-xl border border-[var(--knoux-border)] bg-[var(--knoux-bg-soft)] p-3"><span className="min-w-0 flex-1 truncate font-mono text-xs text-[var(--knoux-text)]" dir="ltr">{path}</span><button type="button" onClick={()=>store.setScanConfig((previous:any)=>({...previous,targetPaths:previous.targetPaths.filter((value:string)=>value!==path)}))} className="grid h-8 w-8 place-items-center rounded-lg text-rose-300 hover:bg-rose-500/10" aria-label={t('Remove path','إزالة المسار')}><FolderMinus className="h-4 w-4"/></button></div>)}</div></section>
   <section className="knoux-glass-panel p-5"><h2 className="flex items-center gap-2 text-base font-black text-[var(--knoux-text)]"><Settings className="h-5 w-5 text-violet-400"/>{t('Limits and safety','الحدود والحماية')}</h2><label className="mt-4 block text-xs font-bold text-[var(--knoux-subtext)]">{t('Minimum file size','الحد الأدنى لحجم الملف')}</label><select value={store.scanConfig.minSizeBytes} onChange={event=>store.setScanConfig((previous:any)=>({...previous,minSizeBytes:Number(event.target.value)}))} className="knoux-select mt-2 w-full text-xs"><option value={0}>{t('All files','كل الملفات')}</option><option value={1024}>1 KB+</option><option value={1048576}>1 MB+</option><option value={10485760}>10 MB+</option><option value={104857600}>100 MB+</option></select><label className="mt-4 flex items-center gap-2 text-xs text-[var(--knoux-text)]"><input type="checkbox" checked={store.scanConfig.includeSubfolders} onChange={event=>store.setScanConfig((previous:any)=>({...previous,includeSubfolders:event.target.checked}))}/>{t('Include nested folders','تضمين المجلدات الفرعية')}</label><div className="mt-4 rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-3 text-xs leading-6 text-emerald-100"><ShieldCheck className="me-2 inline h-4 w-4"/>{t('Windows, Program Files, ProgramData, Recycle Bin, and system-volume paths remain protected.','تظل مسارات Windows وProgram Files وProgramData وسلة المحذوفات ووحدة النظام محمية.')}</div></section>
  </div>
  <section className="space-y-4"><div><h2 className="text-lg font-black text-[var(--knoux-text)]">{t('Choose a verified scan engine','اختر محرك فحص موثق')}</h2><p className="mt-1 text-xs text-[var(--knoux-subtext)]">{t('Every mode states its actual implementation level.','يعرض كل نمط مستوى تنفيذه الحقيقي بوضوح.')}</p></div><div className="grid gap-3 md:grid-cols-2">{scanModes.map(item=>{const Icon=item.icon;const selected=store.scanConfig.scanMode===item.mode;return <button key={item.mode} type="button" onClick={()=>store.setScanConfig((previous:any)=>({...previous,scanMode:item.mode}))} className={`rounded-2xl border p-4 text-start transition ${selected?'border-blue-500/60 bg-blue-500/10 shadow-lg shadow-blue-500/10':'border-[var(--knoux-border)] bg-[var(--knoux-card-bg)] hover:border-[var(--knoux-border-hover)]'}`}><div className="flex items-start gap-3"><div className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl ${selected?'bg-blue-500 text-white':'bg-[var(--knoux-bg-soft)] text-blue-300'}`}><Icon className="h-5 w-5"/></div><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-black text-[var(--knoux-text)]">{t(item.titleEn,item.titleAr)}</h3><span className={`rounded-full px-2 py-0.5 text-[10px] font-black uppercase ${item.state==='implemented'?'bg-emerald-500/15 text-emerald-300':'bg-amber-500/15 text-amber-300'}`}>{item.state}</span></div><p className="mt-2 text-xs leading-5 text-[var(--knoux-subtext)]">{t(item.descriptionEn,item.descriptionAr)}</p></div></div></button>;})}</div><div className="flex justify-end"><button type="button" onClick={store.startScan} disabled={store.isScanning||!store.runtime.available||store.scanConfig.targetPaths.length===0} className="knoux-btn-primary inline-flex min-h-11 items-center gap-2 px-7 disabled:cursor-not-allowed disabled:opacity-50"><Play className="h-5 w-5"/>{t('Start selected scan','بدء الفحص المختار')}</button></div></section>
 </div>;
}
